### ISSUE TITLE
SIGPIPE kills mailexporter silently

### ISSUE THREAD

**Issue by joker234** [cherti/mailexporter#13]
see also issue here: https://github.com/prometheus/prometheus/issues/2241

**Comment by cherti** [comment]
Can you give more context on the circumstances? I cannot reproduce the behavior here, even with `killall -PIPE mailexporter`, which makes fixing a little difficult.

**Comment by joker234** [comment]
With the actual version I cannot reproduce too. Maybe better stall this issue and wait for further bugs about that.

**Comment by cherti** [comment]
Alright, closing then for now.
