### ISSUE TITLE
Missing header fields

### ISSUE THREAD

**Issue by chrko** [cherti/mailexporter#24]
The generated mails don't contain some required headers:
* Date (required)
* Message-ID (highly recommended)

Date: https://tools.ietf.org/html/rfc5322#section-3.6.1 und Format https://tools.ietf.org/html/rfc5322#section-3.3
Message ID: https://tools.ietf.org/html/rfc5322#section-3.6.4

**Comment by cherti** [comment]
Forgot to close this one, finally fixed in a24c2289306904fde6b233f5b5317c82e9013703.
