### ISSUE TITLE
Problems with detectiondir tag in configfile.

### ISSUE THREAD

**Issue by victorlicea** [cherti/mailexporter#33]
Hi! I'm new on this project

I'm searching fix a problem, my exporter doesn't works in the same server that the mail server, I'm using this exporter in a local server but the mail server I'm hired it with Go Daddy and I've a problem with the tag detectiondir 'cause I don't have that directory on my local server, How can I fix that problem? 

Note: the probe-mail is sent succesfully but the metric mail_deliver_success scrape 0 

I'm apologize If my english it's so bad but I'm not english speaker, I hopefully that you can help me!

**Comment by cherti** [comment]
Your mailserver needs to store the delivered Mail in maildir-format on disk and the mailexporter needs to be pointed to that very maildir where the resulting file hits. So this likely means that you need to run mailexporter on the same machine that receives the mail.
