### ISSUE TITLE
Start the endpoint before spamming the prober-goroutines

### ISSUE THREAD

**Issue by cherti** [cherti/mailexporter#8]
Currently the prober-goroutines are spammend and afterwards the HTTP-endpoint is started. this is nice and easy as it is quite sequential, however, it has the disadvantage that with a restart the exporter is scraped as "down" until all the prober-goroutines have started.

Starting the HTTP-endpoint earlier and after starting the probers hooking into it to not exit would be one way of solving this, starting a "prober-spammer"-coroutine would be the other, probably simpler one.

**Comment by el-if** [comment]
I'll do it.
